plugins {
	id 'org.springframework.boot' version '2.7.10'
	id 'io.spring.dependency-management' version '1.0.15.RELEASE'
	id 'java'
}

group = 'com.petra'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '11'

configurations {
	compileOnly {
		extendsFrom annotationProcessor
	}
	all {
		exclude group: 'org.springframework.boot', module: 'spring-boot-starter-logging'
	}
}

repositories {
	mavenCentral()
//	maven { url 'https://repo.spring.io/milestone' }
//	maven { url 'https://repo.spring.io/snapshot' }
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-data-jdbc'
	implementation 'org.springframework.boot:spring-boot-starter-jdbc'
//	implementation 'org.springframework.kafka:spring-kafka'
	// https://mvnrepository.com/artifact/org.codehaus.groovy/groovy-all
	implementation("org.codehaus.groovy:groovy-all:3.0.24")
	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-web'//, version: '2.7.10'
//	implementation group: 'org.springframework.cloud', name: 'spring-cloud-starter-openfeign', version: '3.1.6'

	implementation group: 'org.hibernate', name: 'hibernate-core', version: '5.6.15.Final'
	implementation group: 'org.hibernate', name: 'hibernate-entitymanager', version: '5.6.15.Final'

	implementation group: 'org.postgresql', name: 'postgresql', version: '42.6.0'

	implementation group: 'org.springframework.boot', name: 'spring-boot-starter-data-jpa'//, version: '2.7.10'
	implementation 'org.springframework.boot:spring-boot-starter-log4j2'



//	implementation group: 'org.nanohttpd', name: 'nanohttpd', version: '2.3.1'

//	implementation group: 'com.fasterxml.jackson.core', name: 'jackson-core'//, version: '2.14.1'
//	implementation group: 'com.fasterxml.jackson.core', name: 'jackson-databind'//, version: '2.14.1'
    // https://mvnrepository.com/artifact/com.fasterxml.jackson.core/jackson-core
    implementation 'com.fasterxml.jackson.core:jackson-core:2.20.1'


	compileOnly 'org.projectlombok:lombok'
	runtimeOnly 'org.postgresql:postgresql'
	annotationProcessor 'org.projectlombok:lombok'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
//	testImplementation 'org.springframework.kafka:spring-kafka-test'



	testImplementation 'org.junit.jupiter:junit-jupiter-api:5.8.1'
	testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.8.1'
}

tasks.named('test') {
	useJUnitPlatform()
}
