petra:
#  kafka:
#    servers: localhost:29092
  thread-count: 4
  service-name: TestService

#  services:
#    - name: service_one
#      url: 192.168.0.92
#    - name: service_two
#      url: 192.168.0.92


logging:
  level:
    root: INFO

spring:
  datasource:
    url: jdbc:postgresql://192.168.0.10:5432/petralib
    username: petra
    password: petra4321
    driver-class-name: org.postgresql.Driver
#  jpa:
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    generate-ddl: false
#    show-sql: true
#    entityManagerFactory:
#      name: my-persistence-unit
#    hibernate:
#      ddl-auto: none
#      format_sql: true
#      generate_statistics: true
#    transaction:
#      manager-name: jpaTransactionManager
